population_columns = [
    "Number of children 0-5 (2020)",
    "Number of births to mothers aged 24 and under (2020)",
    "Number of births to mothers aged 25-34 (2020)",
    "Number of births to mothers aged 35 and over (2020)",
    "Total number of births (2020)",
    "Population - all ages (2020)",
    "Birth rate per 1000 (2020)",
    "Number of births to mothers aged 24 and under (2019)",
    "Number of births to mothers aged 25-34 (2019)",
    "Number of births to mothers aged 35 and over (2019)",
    "Total number of births (2019)",
    "Population - all ages (2019)",
    "Birth rate per 1000 (2019)",
    "Number of births to mothers aged 24 and under (2018)",
    "Number of births to mothers aged 25-34 (2018)",
    "Number of births to mothers aged 35 and over (2018)",
    "Total number of births (2018)",
    "Population - all ages (2018)",
    "Birth rate per 1000 (2018)",
    "Number of births to mothers aged 24 and under (2017)",
    "Number of births to mothers aged 25-34 (2017)",
    "Number of births to mothers aged 35 and over (2017)",
    "Total number of births (2017)",
    "Population - all ages (2017)",
    "Birth rate per 1000 (2017)",
]

wimd_columns = [
    "WIMD decile",
    "Number of children living in income deprivation aged 0-4 years old (2019)",
    "WIMD income domain deciles",
    "WIMD income domain - percentage of people in income deprivation",
    "WIMD employment domain deciles",
    "WIMD employment domain - percentage of people in employment deprivation",
    "WIMD health domain deciles",
    "WIMD health domain - GP recorded chronic condition rate (per 100)",
    "WIMD health domain - limiting long-term illness rate (per 100)",
    "WIMD health domain - premature death rate (per 100,000)",
    "WIMD health domain - GP recorded mental health condition rate (per 100)",
    "WIMD health domain - cancer incidence rate (per 100,000)",
    "WIMD health domain - low birth weight, live single births less than 2.5 kg (percentage)",
    "WIMD health domain - percentage of children aged 4-5 who are obese",
    "WIMD education domain deciles",
    "WIMD education domain - foundation phase average point score",
    "WIMD education domain - key stage 2 average point score",
    "WIMD education domain - key stage 4 average point score",
    "WIMD education domain - repeat absenteeism percentage",
    "WIMD education domain - percentage of key stage 4 leavers entering higher education",
    "WIMD education domain - percentage of adults aged 25-64 with no qualifications",
    "WIMD access to services domain deciles",
    "WIMD access to services domain - percentage unavailability of broadband at 30 mb/s",
    "WIMD access to services domain - average public return traveltime to a pharmacy (mins)",
    "WIMD access to services domain - average public return traveltime to a food shop (mins)",
    "WIMD access to services domain - average public return traveltime to a GP surgery (mins)",
    "WIMD access to services domain - average public return traveltime to a post office (mins)",
    "WIMD access to services domain - average public return traveltime to a primary school (mins)",
    "WIMD access to services domain - average public return traveltime to a public library (mins)",
    "WIMD access to services domain - average public return traveltime to a sports facility (mins)",
    "WIMD access to services domain - average public return traveltime to a secondary school (mins)",
    "WIMD access to services domain - average private return traveltime to a pharmacy (mins)",
    "WIMD access to services domain - average private return traveltime to a food shop (mins)",
    "WIMD access to services domain - average private return traveltime to a GP surgery (mins)",
    "WIMD access to services domain - average private return traveltime to a post office (mins)",
    "WIMD access to services domain - average private return traveltime to a primary school (mins)",
    "WIMD access to services domain - average private return traveltime to a public library (mins)",
    "WIMD access to services domain - average private return traveltime to a sports facility (mins)",
    "WIMD access to services domain - average private return traveltime to a secondary school (mins)",
    "WIMD access to services domain - average private return traveltime to a petrol station (mins)",
    "WIMD housing domain deciles",
    "WIMD housing domain - percentage of people in overcrowded households",
    "WIMD housing domain - percentage likelihood of poor quality housing",
    "WIMD housing domain - percentage likelihood of housing containing serious hazards",
    "WIMD housing domain - percentage likelihood of housing being in disrepair",
    "WIMD physical environment domain deciles",
    "WIMD physical environment domain - population weighted average concentration value for no2",
    "WIMD physical environment domain - population weighted average concentration value for particulates <10μm",
    "WIMD physical environment domain - population weighted average concentration value for particulates <2.5μm",
    "WIMD physical environment domain - households at risk of flooding score",
    "WIMD physical environment domain - proximity to accessible natural green space score (percentage of households)",
    "WIMD physical environment domain - ambient green space score",
    "WIMD community safety domain deciles",
    "WIMD community safety domain - police recorded criminal damage (rate per 100)",
    "WIMD community safety domain - police recorded violent crime (rate per 100)",
    "WIMD community safety domain - police recorded anit-social behaviour (rate per 100)",
    "WIMD community safety domain - police recorded burglary (rate per 100)",
    "WIMD community safety domain - police recorded theft (rate per 100)",
    "WIMD community safety domain - fire incidences (rate per 100)",
]

fpp_columns = ["Foundation phase (mean difference)"]

rural_columns = [
    "Rural-Urban",
    "Rural-Urban detailed classification",
    "Rural/ Urban Settlement Classification (RU) Name",
]

population_columns_for_df = [
    "Number of children 0-5 (2020)",
    "Number of births to mothers aged 24 and under (2020)",
    "Number of births to mothers aged 25-34 (2020)",
    "Number of births to mothers aged 35 and over (2020)",
    "Total number of births (2020)",
    "Population - all ages (2020)",
    "Birth rate per 1000 (2020)",
    "Number of births to mothers aged 24 and under (2019)",
    "Number of births to mothers aged 25-34 (2019)",
    "Number of births to mothers aged 35 and over (2019)",
    "Total number of births (2019)",
    "Population - all ages (2019)",
    "Birth rate per 1000 (2019)",
    "Number of births to mothers aged 24 and under (2018)",
    "Number of births to mothers aged 25-34 (2018)",
    "Number of births to mothers aged 35 and over (2018)",
    "Total number of births (2018)",
    "Population - all ages (2018)",
    "Birth rate per 1000 (2018)",
    "Number of births to mothers aged 24 and under (2017)",
    "Number of births to mothers aged 25-34 (2017)",
    "Number of births to mothers aged 35 and over (2017)",
    "Total number of births (2017)",
    "Population - all ages (2017)",
    "Birth rate per 1000 (2017)",
]

wimd_columns_for_df = [
    "Number of children living in income deprivation aged 0-4 years old (2019)",
    "WIMD income domain deciles",
    "WIMD income domain - percentage of people in income deprivation",
    "WIMD employment domain deciles",
    "WIMD employment domain - percentage of people in employment deprivation",
    "WIMD health domain deciles",
    "WIMD health domain - GP recorded chronic condition rate (per 100)",
    "WIMD health domain - limiting long-term illness rate (per 100)",
    "WIMD health domain - premature death rate (per 100,000)",
    "WIMD health domain - GP recorded mental health condition rate (per 100)",
    "WIMD health domain - cancer incidence rate (per 100,000)",
    "WIMD health domain - low birth weight, live single births less than 2.5 kg (percentage)",
    "WIMD health domain - percentage of children aged 4-5 who are obese",
    "WIMD education domain deciles",
    "WIMD education domain - foundation phase average point score",
    "WIMD education domain - key stage 2 average point score",
    "WIMD education domain - key stage 4 average point score",
    "WIMD education domain - repeat absenteeism percentage",
    "WIMD education domain - percentage of key stage 4 leavers entering higher education",
    "WIMD education domain - percentage of adults aged 25-64 with no qualifications",
    "WIMD access to services domain deciles",
    "WIMD access to services domain - percentage unavailability of broadband at 30 mb/s",
    "WIMD access to services domain - average public return traveltime to a pharmacy (mins)",
    "WIMD access to services domain - average public return traveltime to a food shop (mins)",
    "WIMD access to services domain - average public return traveltime to a GP surgery (mins)",
    "WIMD access to services domain - average public return traveltime to a post office (mins)",
    "WIMD access to services domain - average public return traveltime to a primary school (mins)",
    "WIMD access to services domain - average public return traveltime to a public library (mins)",
    "WIMD access to services domain - average public return traveltime to a sports facility (mins)",
    "WIMD access to services domain - average public return traveltime to a secondary school (mins)",
    "WIMD access to services domain - average private return traveltime to a pharmacy (mins)",
    "WIMD access to services domain - average private return traveltime to a food shop (mins)",
    "WIMD access to services domain - average private return traveltime to a GP surgery (mins)",
    "WIMD access to services domain - average private return traveltime to a post office (mins)",
    "WIMD access to services domain - average private return traveltime to a primary school (mins)",
    "WIMD access to services domain - average private return traveltime to a public library (mins)",
    "WIMD access to services domain - average private return traveltime to a sports facility (mins)",
    "WIMD access to services domain - average private return traveltime to a secondary school (mins)",
    "WIMD access to services domain - average private return traveltime to a petrol station (mins)",
    "WIMD housing domain deciles",
    "WIMD housing domain - percentage of people in overcrowded households",
    "WIMD housing domain - percentage likelihood of poor quality housing",
    "WIMD housing domain - percentage likelihood of housing containing serious hazards",
    "WIMD housing domain - percentage likelihood of housing being in disrepair",
    "WIMD physical environment domain deciles",
    "WIMD physical environment domain - population weighted average concentration value for no2",
    "WIMD physical environment domain - population weighted average concentration value for particulates <10μm",
    "WIMD physical environment domain - population weighted average concentration value for particulates <2.5μm",
    "WIMD physical environment domain - households at risk of flooding score",
    "WIMD physical environment domain - proximity to accessible natural green space score (percentage of households)",
    # Note: Is this supposed to be here? given the variable above? 
    # "wimd_physical_environment_domain_proximity_to_accessible_natural_green_space_score_percentage_of_households",
    "WIMD physical environment domain - ambient green space score",
    "WIMD community safety domain deciles",
    "WIMD community safety domain - police recorded criminal damage (rate per 100)",
    "WIMD community safety domain - police recorded violent crime (rate per 100)",
    "WIMD community safety domain - police recorded anit-social behaviour (rate per 100)",
    "WIMD community safety domain - police recorded burglary (rate per 100)",
    "WIMD community safety domain - police recorded theft (rate per 100)",
    "WIMD community safety domain - fire incidences (rate per 100)",
]

fpp_columns_for_df = [
    "Foundation phase (mean difference)",
    "Foundation phase performance",
]

rural_columns_for_df = ["Rural-Urban", "Rural-Urban detailed classification"]